### PR TITLE
[16.0][3891][ADD] mrp_production_move_line_auto_fill

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
[3891](https://www.quartile.co/web#id=3891&menu_id=517&cids=3&model=project.task&view_type=form)
Depends on https://github.com/qrtl/rco-oca/pull/7

### CODE REVIEW

**Comment by AungKoKoLin1997** [comment]
@rinaldifirdaus  Please help me to review this PR first.

**Review by yostashiro — COMMENTED** [review]
@AungKoKoLin1997 Please seek the possibility of refactoring stock_move_line_auto_fill to avoid duplicating the logic in this module.

**Review by rinaldifirdaus — APPROVED** [review]

**Comment by rinaldifirdaus** [comment]
@yostashiro san, kindly help to merge this PR. i have updated the PR with latest oca repo. thanks

**Comment by yostashiro** [comment]
@rinaldifirdaus Please add translation.

**Comment by rinaldifirdaus** [comment]
@yostashiro san, reminder, please kindly help merge this PR.

**Pull request merged**
